swagger: '2.0'
info:
  title: Url2Png API
  description: Convert a URL to a PNG image and download.
  version: 1.0.0
host: url2png.spatialdev.com
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /url2png:
    post:
      summary: Convert webpage to PNG.
      description: The url2png endpoint accepts a URL and returns a link to download
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              url:
                type: string
                description: URL of webpage to convert
              viewport_width:
                type: number
                format: integer
                description: The width of the produced PNG (default is 1440px)
                required: false
              delay:
                type: number
                description: The time delay (ms) before executing image capture (default is 5000 ms)
                required: false
                format: integer

      responses:
        '200':
          description: An object with success message and link to download the image.
          schema:
            type: object
            properties:
              message:
                type: string
                description: success
              downloadURL:
                type: string
                description: The relative URL for download of the captured image. Root will be the same as the API.
        '400':
          description: Error due to failure to submit required parameters.
          schema:
            type: object
            properties:
              message:
                type: string
                description: No URL to print in post data
              status:
                type: string
                description: Error Status
        '500':
          description: Server error.
          schema:
            type: object
            properties:
              message:
                type: string
                description: Error message
              status:
                type: string
                description: Error Status
